config/routes.rb
Test123::Application.routes.draw do
  resources :names
  get "vote" => "names#vote"
  post "vote" => "names#voteresult"

end

app/models/name.rb
class Name < ActiveRecord::Base
  attr_accessible :count, :name, :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  # GET /names
  # GET /names.json
  def index
    @names = Name.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @names }
    end
  end

  # GET /names/1
  # GET /names/1.json
  def show
    @name = Name.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/new
  # GET /names/new.json
  def new
    @name = Name.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(params[:name])

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render json: @name, status: :created, location: @name }
      else
        format.html { render action: "new" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /names/1
  # PUT /names/1.json
  def update
    @name = Name.find(params[:id])

    respond_to do |format|
      if @name.update_attributes(params[:name])
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name = Name.find(params[:id])
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url }
      format.json { head :no_content }
    end
  end

  def vote
    @names = Name.all(:order => 'RANDOM()', :limit => 2)
    @names.each do |name|
      name.count +=1
      name.save
    end
  end

  def voteresult
    @winner = Name.find_by_id(params["winner"])
    @winner.score +=1
    @winner.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test123</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<h1>Listing names</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Score</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= name.name %></td>
    <td><%= name.score %></td>
    <td><%= name.count %></td>
    <td><%= link_to 'Show', name %></td>
    <td><%= link_to 'Edit', edit_name_path(name) %></td>
    <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Name', new_name_path %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @name.name %>
</p>

<p>
  <b>Score:</b>
  <%= @name.score %>
</p>

<p>
  <b>Count:</b>
  <%= @name.count %>
</p>


<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/names/vote.html.erb
<%= form_tag("/vote", method: "post") do %>
    <button name="winner" value="<%= @names[0].id %>"><%= @names[0].name %></button>
    <button name="winner" value="<%= @names[1].id %>"><%= @names[1].name %></button>
<% end %>

app/views/names/voteresult.html.erb
<p>Winner: <%= @winner.name %></p>
<p>Count: <%= @winner.count %></p>
<p>Score: <%= @winner.score %></p>